name: Build XCFramework

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List available SDKs
        run: xcodebuild -showsdks

    #   - name: Build macOS framework
    #     run: |
    #       xcodebuild \
    #         -project MyProject.xcodeproj \
    #         -scheme MyFramework \
    #         -configuration Release \
    #         -sdk macosx \
    #         -arch arm64 \
    #         -arch x86_64 \
    #         BUILD_DIR=build \
    #         BUILD_ROOT=build \
    #         clean build
